### ISSUE TITLE
Error on the table renderer when displaying json

### ISSUE THREAD

**Issue by DTAIEB** [ibm-watson-data-lab/pixiedust#641]
As a user, I want to display json value and not get an error on the table renderer

### Expected behavior
Display the data as a table as expected

### Steps to reproduce the behavior
```
import pixiedust
display([{"year":2010, "category": 'Camping Equipment', "unique_customers":3},
 {"year":2010, "category": 'Golf Equipment', "unique_customers":1},
 {"year":2010, "category": 'Mountaineering Equipment',"unique_customers": 1},
 {"year":2010, "category": 'Outdoor Protection', "unique_customers":2},
 {"year":2010, "category": 'Personal Accessories', "unique_customers":2},
 {"year":2011, "category": 'Camping Equipment', "unique_customers":4},
 {"year":2011, "category": 'Golf Equipment', "unique_customers":5},
 {"year":2011, "category": 'Mountaineering Equipment',"unique_customers":2},
 {"year":2011, "category": 'Outdoor Protection', "unique_customers":4},
 {"year":2011, "category": 'Personal Accessories', "unique_customers":2},
 {"year":2012, "category": 'Camping Equipment', "unique_customers":5},
 {"year":2012, "category": 'Golf Equipment', "unique_customers":5},
 {"year":2012, "category": 'Mountaineering Equipment',"unique_customers": 3},
 {"year":2012, "category": 'Outdoor Protection', "unique_customers":5},
 {"year":2012, "category": 'Personal Accessories', "unique_customers":3},
 {"year":2013, "category": 'Camping Equipment', "unique_customers":8},
 {"year":2013, "category": 'Golf Equipment', "unique_customers":5},
 {"year":2013, "category": 'Mountaineering Equipment',"unique_customers": 3},
 {"year":2013, "category": 'Outdoor Protection',"unique_customers": 8},
 {"year":2013, "category": 'Personal Accessories',"unique_customers": 4}])
```

Get this error:
![image](https://user-images.githubusercontent.com/4912140/37368248-099f218a-26dc-11e8-9cb9-3c124356d660.png)

Error log:
```
2018-03-13 16:31:39,522 - pixiedust.display.display.Display - ERROR - Unexpected error while trying to render BaseChartDisplay
Traceback (most recent call last):
  File "/Users/dtaieb/watsondev/workspaces/cds_workspace/pixiedust-gateway-work/pixiedust/display/chart/renderers/baseChartDisplay.py", line 428, in doRender
    chartFigure = self.doRenderChart()
  File "/Users/dtaieb/watsondev/workspaces/cds_workspace/pixiedust-gateway-work/pixiedust/display/chart/renderers/table/TableDisplay.py", line 14, in doRenderChart
    table_nosearch=self.options.get("table_nosearch", "false"))
  File "/Users/dtaieb/watsondev/workspaces/cds_workspace/pixiedust-gateway-work/pixiedust/display/display.py", line 303, in renderTemplate
    return self.env.getTemplate(templateName).render(self._getTemplateArgs(**kwargs))
  File "/Users/dtaieb/anaconda/envs/dashboard/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/dtaieb/anaconda/envs/dashboard/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/dtaieb/anaconda/envs/dashboard/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "table.html", line 160, in top-level template code
  File "/Users/dtaieb/anaconda/envs/dashboard/lib/python3.5/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
  File "/Users/dtaieb/watsondev/workspaces/cds_workspace/pixiedust-gateway-work/pixiedust/display/chart/display.py", line 43, in count
    return createDataframeAdapter(self.entity).count()
  File "/Users/dtaieb/watsondev/workspaces/cds_workspace/pixiedust-gateway-work/pixiedust/utils/dataFrameAdapter.py", line 44, in createDataframeAdapter
    raise ValueError("Invalid argument")
ValueError: Invalid argument
```

**Comment by DTAIEB** [comment]
Fix has been released on PyPI with 1.1.9
