### ISSUE TITLE
Unable to install on Windows 10

### ISSUE THREAD

**Issue by maydanw** [ibm-watson-data-lab/pixiedust#658]
This was the Traceback (I did replaced my own username with Username at the last line)
Traceback (most recent call last):
```  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-pixiedust.EXE\__main__.py", line 9, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\install\pixiedustapp.py", line 41, in main
    PixiedustJupyterApp.launch_instance()
  File "c:\programdata\anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-2>", line 2, in initialize
  File "c:\programdata\anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\traitlets\config\application.py", line 296, in initialize
    self.parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "c:\programdata\anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\traitlets\config\application.py", line 514, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "c:\programdata\anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\traitlets\config\application.py", line 452, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "c:\programdata\anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\programdata\anaconda3\lib\site-packages\jupyter_core\application.py", line 239, in initialize
    self.parse_command_line(argv)
  File "c:\programdata\anaconda3\lib\site-packages\install\createKernel.py", line 150, in parse_command_line
    self.download_spark(silent, silent_spark_version)
  File "c:\programdata\anaconda3\lib\site-packages\install\createKernel.py", line 409, in download_spark
    self.extract_temp_file(temp_file, self.spark_home)
  File "c:\programdata\anaconda3\lib\site-packages\install\createKernel.py", line 479, in extract_temp_file
    tar = tarfile.open(temp_file.name, "r:gz")
  File "c:\programdata\anaconda3\lib\tarfile.py", line 1586, in open
    return func(name, filemode, fileobj, **kwargs)
  File "c:\programdata\anaconda3\lib\tarfile.py", line 1633, in gzopen
    fileobj = gzip.GzipFile(name, mode + "b", compresslevel, fileobj)
  File "c:\programdata\anaconda3\lib\gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Username\\AppData\\Local\\Temp\\tmp2w2ksjng.tgz'```

**Comment by ptitzler** [comment]
Unfortunately PixieDust is currently not supported on Windows

**Comment by DTAIEB** [comment]
Closing this issue since there are no plans to support Windows in the near future
